url: https://parpersson.github.io/stannatiden
baseurl:

# Site settings
title: Stanna tiden - Portr채ttfoto i Stockholm
email: info@parenglund.se
description: "Portr채ttfotografering av folk du tycker om."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: P채r Englund
  pic: 1
  position: Inneh책llsproducent
  social:
    - title: linkedin
      url: https://se.linkedin.com/in/parenglund
    - title: flickr
      url: https://www.flickr.com/photos/parenglund/
    - title: pinterest
      url: https://www.pinterest.se/englundpar/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: Stockholm
  - line: Karlstad

# Build settings
markdown: kramdown
permalink: pretty
